### ISSUE TITLE
1.1.5 Non-functional Requirements

### ISSUE THREAD

**Issue by SaltedEggYok** [SaltedEggYok/INF2001_P6-7#10]
Task Description: This task involves the analysis of client-provided information to pinpoint non-functional requirements which greatly enhances user experience, providing higher business value to the application.

Goal of task: The task aims to ascertain all non-functional requirements of the application that should be implemented.

Success of the task is determined by the accurate identification of the non-functional requirements.

Allocated time: 2 hours.

Start Date: 13/9/2023
End Date: 13/9/2023

Prioritity: High

**Comment by samuelgjy** [comment]
Work Description

**Describe the work done in detail:**
In this phase of the project, the team is focused on gathering documentations on the performance, availability and scalability of the application, which is critical for providing accurate route estimations and supporting multiple scheduling change requests from managers. Therefore, with the successful identification of the non-functional requirements, the task has been successfully completed.

Start Date: 13/9/2023
End Date 13/9/2023
