### ISSUE TITLE
1.2.3 Use Case Descriptions 1-3

### ISSUE THREAD

**Issue by SaltedEggYok** [SaltedEggYok/INF2001_P6-7#12]
Description of task: This task involves providing the accurate capturing of the functional requirements and description of any interaction with the software for UC-1 to UC-3. These should describe all possible cases of the respective use cases.

Goal of task: The task aims to provide a written description of how actors will be able to perform tasks on the application. It will capture all possible scenarios in the respective use case.

Success of the task is dependent on the accurate description and capturing of the functionalities of use cases UC-1 to UC-10.

Allocated time: 2 days

Start Date:  19/9/2023
End Date:  21/9/2023

Owner: Zi bin
Status: Completed

Priority: High

**Comment by ZIBINNG** [comment]
Work Description

Describe the work done in detail:

In this task, I was able to effectively extract key information for the use case description. Overall the task was successful as I managed to complete the use case description with the right information.

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule and does not need to be committed to the repository.

Start Date: 19/9/2023
End Date 21/9/2023
