### ISSUE TITLE
1.2.4 Activity Diagram

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#15]
Description of task: This task entails designing and producing an Activity Diagram to illustrate the processes involving the user, system, and database when performing a specific action. The selected action involves a coach crew member logging into the app to verify their weekly working hours.

Goal of task: The goal of this task is to provide a clear visual representation of the workflow and interactions between the user, system, and database during the process of a coach crew member verifying their weekly working hours.

Success of this task depends on the clarity and comprehensibility of the Activity Diagram, ensuring that it effectively conveys the steps and interactions involved in the user's action of verifying working hours.

Allocated time: 2 Hours

Start Date: 22/9/2023
End Date: 22/9/2023

Owner: Wong Yok Hung
Status: Completed

Priority: Medium

**Comment by SaltedEggYok** [comment]
Work Description

Describe the work done in detail:
In this task, a linear diagram was designed first linking processes and decisions from the start of the activity to the end of the acitivity. From there, swimlanes were added and the diagram was divided into "User", "System" and "Database", the initial linear diagram was slightly redesigned and shifted around to fit into the correct lanes. 

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule and does not need to be committed to the repository.

Start Date : 22/9/2023
End Date: 22/9/2023
