### ISSUE TITLE
1.1.7 Project Schedule Planning

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#16]
Task Description:
This task involves creating a visual representation of the project schedule which entails the project's tasks, durations, the individuals or teams responsible for them, and any task dependencies that may exist.

Task Goals:
The primary objectives of this task are as follows:

- To meticulously plan and organize the project's tasks.
- To ensure that each task has been assigned an appropriate amount of time for completion.
- To align the tasks with the overarching goals and vision of the project.
- To maintain a chart that accurately reflects the current status and progress of the project.

Completion Criteria:
The completion criteria for this task are as follows:

- All planned project tasks have been incorporated into the chart.
- Every task in the chart has been assigned the necessary resources.
- The tasks in the chart are consistent with the project's defined goals and vision.
- The chart accurately portrays the project's current status and progress.

Start Date: 10 September 2023
End Date: 22 September 2023

Who is the owner?
All

Task Status:
The task is currently marked as "In-Progress."

Task Priority:
This task holds a high priority within the project's scope.

**Comment by davidlane23** [comment]
Work Description

Describe the work done in detail:

In this task, the team utilized a waterfall approach and had planned the relevant tasks that had to be performed. For M1, this included the detailing of all requirements in the M1 report and the updating of the kanban board to ensure everyone is on the same page. A gantt chart was also created to illustrate the expected deadlines of each task, allowing the team to keep the project on track. 

The team successfully planned and update relevant tasks where completed, accurately portraying the projects current status.

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule and does not need to be committed to the repository.

Start Date: 10/9/2023
End Date 22/9/2023
