### ISSUE TITLE
2.1.3 Design Component Diagram

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#18]
Description of task: This task involves the designing of the component diagram for the application. correct grouping of components within the diagram is key to ensuring that the relationship between the components are well captured.

Goal of task: The task aims to correctly identify the correct components based off the class diagram and ensure that these components all adhere to single responsibility.

Success of the task is dependent on the accurate depiction of how the class diagram is dissected and grouped into the correct components and the diagram must illustrate the relationship between each component well.

Allocated time: 1 week

Start Date: 12/10/2023
End Date: 19/10/2023

Owner: To Be Scheduled
Status: To Do

Priority: Medium

**Comment by ZIBINNG** [comment]
I have successfully completed the task of designing the component diagram for the application. The diagram accurately identifies and groups components based on the class diagram, adhering to the principle of single responsibility. The relationships between each component are clearly and correctly illustrated, meeting the task's goal of providing an accurate depiction of how the class diagram is dissected and grouped. This ensures that the component diagram serves as a reliable guide for the development and integration of the application's components.

After the initial draft, the diagram was then separately revisited and I made necessary changes to suit what the class diagram.


Start Date: 14/10/2023
End Date: 21/10/2023

Status: Completed
