### ISSUE TITLE
[OBSOLETE]  2.2.2 Sequence Diagram

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#21]
This task has been superseded by 2.2.2.1 Create Sequence Diagram for UC4 and 2.2.2.2 Create Sequence Diagram for UC5

**Comment by davinlim23** [comment]
This task has been superseded by 2.2.2.1 Create Sequence Diagram for UC4 and 2.2.2.2 Create Sequence Diagram for UC5
