### ISSUE TITLE
3.2.1 Black-box Testing

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#23]
Description of the task: This task involves the documentation of the decision table testing methodology for a prominent method within the system.

Goal of the task: The goal of this task is to ensure proper testing and documentation of how one would test a specific method within  a class to showcase proper testing of the application.

Success of this task is dependent on the correct documenting of all test cases relating to the method chosen and the expected output from a particular input

Allocated time: 4 days

Start Date: 12/11/2023
End Date: 16/11/2023

Owner: Thaddeus Kwok
Status: In Progress

Priority: High

**Comment by Thaddaeus-K** [comment]
Equivalence Partitioning and Boundary Value Analysis was conducted on the maximum working hours limit and vehicle fleet limit to test the workability of the limits imposed. Decision table testing was conducted on the allocateJob() function to cover all possible scenarios when a manager is trying to allocate jobs to coach staff and assign coaches to jobs. The decision table is also reduced afterwards to reflect the effects of different causes.


Start Date: 12/11/2023
End Date: 16/11/2023
