### ISSUE TITLE
3.2.2 White-box Testing

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#24]
Description of the task: This task involves the documentation of the pseudocode behind the chosen method and the control flow graph for that method.

Goal of the task: The goal of this task is to ensure proper documentation and accurate diagramming of the control flow graph in order to ensure that the technical costs of the task can be estimated and represent the flow of the method.

Success of this task is dependent on the correct description of the method by utilizing psuedocode and accurate diagramming of the control flow graph.

Allocated time: 4 days

Start Date: 12/11/2023
End Date: 16/11/2023

Owner: Lucas Liew
Status: In Progress

Priority: High

**Comment by liewlucas** [comment]
The group have done a detailed pseudocode for the method updateExistingJob(), focusing on updating the details of an existing job within a system. it involves  taking in jobID, jobLocation, jobDistance and jobTime and updates the details of an existing Job object.The Cyclomatic Complexity of the method has been calculated using the formula E - N + 2, resulting in a value of 4. Three basis paths have been identified, each representing distinct sequences of execution, and corresponding test cases have been outlined for scenarios such as updating an existing job, attempting to update a completed job, and attempting to update a non-existent job.

Start Date: 12/11/2023
End Date: 21/11/2023
