### ISSUE TITLE
1.2.3.2 Use Case Descriptions 5

### ISSUE THREAD

**Issue by davidlane23** [SaltedEggYok/INF2001_P6-7#28]
Description of task: This task involves providing the accurate capturing of the functional requirements and description of any interaction with the software for UC5. 

Goal of task: The task aims to provide a written description of how the actors will be able to perform tasks on the application. It will capture all possible steps a user can take to perform the task.

Success of the task is dependent on the accurate description and capturing of the functionalities of the use case UC5.

Allocated time: 2 days

Start Date:  19/9/2023
End Date:  21/9/2023

Owner: Samuel Goh
Status: Completed

Priority: High

**Comment by samuelgjy** [comment]
Work Description:

I focused on capturing the functional requirements and outlining interactions within the software for UC5. I ensured a comprehensive documentation of all potential user actions for tasks linked to UC5. This includes defining the preconditions and postconditions, main success scenarios and alternative scenarios.

Impact on the Completion Deadline:
The task was accomplished within the allocated two-day window, aligning seamlessly with the project's overall schedule. Therefore, there was no impact on the completion deadline.

Changes to Success/Completion Criteria:
The task achieved success by meeting the stipulated timeframe and accurately fulfilling the specified requirements.

Start Date: 19/9/2023
End Date: 21/9/2023
