### ISSUE TITLE
2.2.1 Design Class Diagram

### ISSUE THREAD

**Issue by davidlane23** [SaltedEggYok/INF2001_P6-7#30]
Description of task: This task involves the designing of class diagrams for the application

Goal of task: The task aims to provide an overview of the relationship between the object classes.

Success of the task is dependent on the accurate depiction of the relationship between the object classes in the diagram.

Allocated time: 1 week

Start Date:  28/9/23
End Date:  5/10/23

Owner: To Be Scheduled
Status:  To Do

Priority:  High

**Comment by SaltedEggYok** [comment]
Work Description

Describe the work done in detail:
In this task, the core entity classes, attributes and methods were first identified and added to the class diagram. Following that, respective control classes and boundary classes were added to the diagram. Then relationships are defined and connected together. 

After the initial draft, the diagram was then separately broken down into components to facilitate the creation of the component diagram.

The class diagram was revisited after completion of the component diagram and the interface classes were added and their relationships with the control classes were established.

Start Date: 28/9/23
End Date: 5/10/23

Status: Completed
