### ISSUE TITLE
2.2.2.2 Create Sequence Diagram for UC5

### ISSUE THREAD

**Issue by davidlane23** [SaltedEggYok/INF2001_P6-7#31]
Description of task: This task involves the designing of the sequence diagram for UC5.

Goal of task: The task aims to provide an overview of how objects and processes work together within the application for use case 5, depicting how and what is needed to provide the functionality.

Success of the task is dependent on the accurate depiction of how users within the system are able to interact with the processes that the system provides based on UC5.

Allocated time: 1 week

Start Date:  6/10/2023
End Date:  13/10/2023

Owner: To Be Scheduled
Status:  To Do 

Priority:  Medium

**Comment by SaltedEggYok** [comment]
Work Description

Describe the work done in detail:
Classes relavant to Use Case 5 were identified and laid out to build up a skeleton for the sequence diargam. The processes between the classes were then traced out and added with the appropriate lifebars, arrows and descriptors. Frequent back and forth with the class diagram was done to ensure consistency was maintained between the 2 diagrams.

This work does not need to be committed to the repository. This phase of work was also planned and executed within the allocated time frame which aligns with the overall project schedule, ensuring that the team is on track for completion in M2.

Start Date: 6/10/23
End Date: 13/10/23
