### ISSUE TITLE
1.2.3.4 Use Case Descriptions 9

### ISSUE THREAD

**Issue by davidlane23** [SaltedEggYok/INF2001_P6-7#33]
Description of task: This task involves providing the accurate capturing of the functional requirements and description of any interaction with the software for UC8.

Goal of task: The task aims to provide a written description of how actors will be able to perform tasks on the application.  It will capture all possible steps a user can take to perform the task.

Success of the task is dependent on the accurate description and capturing of the functionalities of use case UC8.

Allocated time: 2 days

Start Date:  19/9/2023
End Date:  21/9/2023

Owner: Thaddeus Kwok
Status: Completed

Priority: High

**Comment by samuelgjy** [comment]
Work Description:

My primary focus was on documenting the functional requirements and outlining the software interactions related to UC9. I made sure to create comprehensive documentation covering all potential user actions for tasks associated with UC9. This involved defining preconditions, postconditions, main success scenarios, and alternative scenarios.

Impact on Project Schedule:
I successfully completed this task within the allotted two-day timeframe and seamlessly aligning it with the overall project schedule. As a result, there was no impact on the project's completion deadline.

Changes to Criteria for Success/Completion:
This task achieved its objectives by meeting the specified timeframe and accurately fulfilling the defined requirements.

Start Date: September 19, 2023
End Date: September 21, 2023
