### ISSUE TITLE
Review Use Case Description

### ISSUE THREAD

**Issue by davidlane23** [SaltedEggYok/INF2001_P6-7#35]
Task Description: This task involves the reviewing of the use case descriptions to ensure that format of descriptions are consistent and content is clear and concise.

Goal of task: This task aims to ensure the correctness and consistency of all use case descriptions.

Success of the task is determined by the successful review of all use case descriptions.
Allocated time: 2 hours.

Start Date: 22/9/2023
End Date: 23/9/2023

Priority: High

Task owner: Thaddeus Kwok

Status : In progress

**Comment by samuelgjy** [comment]
Work Description:

I was tasked on documenting the functional requirement and outlining the software interactions related to all Use case description. I made sure to create comprehensive documentation covering all potential user actions for tasks associated with all use case. This involved defining preconditions, postconditions, main success scenarios, and alternative scenarios.

I effectively executed this task within the designated timeframe and seamlessly integrating it with the project's overarching schedule. As a result, there was no impact to the project's completion deadline.

Start Date: 22/9/2023
End Date: 23/9/2023

Status: Completed.
