### ISSUE TITLE
Review Use Case Diagram

### ISSUE THREAD

**Issue by davidlane23** [SaltedEggYok/INF2001_P6-7#36]
Task Description: This task involves the review of the use case diagram to ensure that all functional requirements have been correctly translated into the use case diagram.

Goal of task: This task aims to ensure the correctness of the use case diagram.

Success of the task is determined by the successful review of the use case diagram.
Allocated time: 2 hours.

Start Date: 22/9/2023
End Date: 23/9/2023

Priority: High

Task owner: Ng Zi Bin

Status : In progress

**Comment by ZIBINNG** [comment]
Work Description

Describe the work done in detail:
In this task, I review all of the use case diagram to ensure that all functional requirements have been correctly translated into the use case diagram. 

With the successful reviewing of use case diagram, the task has been successfully completed.

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule and does not need to be committed to the repository.

Start Date : 22/9/2023
End Date: 23/9/2023
