### ISSUE TITLE
Product Overview and Functionality

### ISSUE THREAD

**Issue by davidlane23** [SaltedEggYok/INF2001_P6-7#37]
Description of task: This task involves providing the accurate detailing of the the product overview and functionality for the M1 report.

Goal of task: The task aims to provide a written overview of the product and ensure that all key functionality is captured.

Success of the task is dependent on the accurate detailing and provision of all functionalities in which the product is supposed to offer.

Allocated time: 2 days

Start Date:  19/9/2023
End Date:  21/9/2023

Owner: Wong Yok Hung
Status: Completed

Priority: High

**Comment by SaltedEggYok** [comment]
Work Description

Describe the work done in detail: Section 2 with the M1 report covering the product overview and functionality of the product was written, vetted and finalized.

Start Date: 19/9/2023
End Date: 21/9/2023
