### ISSUE TITLE
Introduction, Project Scope and Literature Review

### ISSUE THREAD

**Issue by davidlane23** [SaltedEggYok/INF2001_P6-7#38]
Description of task: This task involves the detailing of the the background information of the product including but not limited to research into the industry, problem statement of the project and what the project entails.

Goal of task: The task aims to provide an introduction to the project requirements and why the system is required while also providing a comprehensive review of the industry. 

Success of the task is dependent on the accurate understanding of the project domain and detailing all information pertaining the scope of the project.

Allocated time: 2 days

Start Date:  19/9/2023
End Date:  21/9/2023

Owner: Ng Zi Bin
Status: Completed

Priority: High

**Comment by ZIBINNG** [comment]
Work Description

Describe the work done in detail:
In this task, I provided an introduction to the project requirements and why the system is required while also providing a comprehensive review of the industry.

With research and accurate understanding of the project domain and detailing all information pertaining the scope of the project. , the task has been successfully completed.

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule and does not need to be committed to the repository.

Start Date : 19/9/2023
End Date: 21/9/2023
