### ISSUE TITLE
M1 Retrospection 1

### ISSUE THREAD

**Issue by davinlim23** [SaltedEggYok/INF2001_P6-7#39]
Description of task: This task involves the retrospection of team members for the M1 milestone. 

Goal of task: The task aims to identify the strengths, weaknesses and any issues a team member might face. Some key questions include

**What went well in Milestone one?**

Success of the task is dependent on how well the team is able to discuss their issues and understand more about their teammates.

Allocated time: 3 day

Start Date:  5/10/2023
End Date:  8/10/2023

Owner: All group members
Status: In Progress

Priority: High

**Comment by davinlim23** [comment]
Work Description

Describe the work done in detail:

In this task, the team was able to discuss their respective viewpoints and the specific things that had gone well for the M1 project. This allowed the team to understand what aspects of the project could be utilized for the M2 milestone. For my personal opinion, I felt that each member of the team was able to have effective communication, providing better decision making and ensure consistency in workload. 

For example, when one of us had troubles in difficulty in understanding why we had grouped certain functional requirements together for a use case, he was able to quickly communicate this question and ensure that he was not left behind. Some other aspects which went well was the planning of the project as it was a clear breakdown of what had to be done for M1, ensuring that the team would remain on track and hit deadlines. Tools such as gantt charts and work breakdown structures were designed to ensure that this would be the case.

This task was a success as we were able to extract the key details which pertained to the positives in M1. This work does not need to be committed to the repository. This phase of work was also planned and executed within the allocated time frame which aligns with the overall project schedule, ensuring that the team is on track for completion in M2.

Start Date: 6/10/2023
End Date: 6/10/2023

**Comment by ZIBINNG** [comment]
Work Description

Describe the work done in detail:

In reflecting on the M1 milestone, our team demonstrated a strong ability to adapt and innovate, which I believe will serve us well as we move into the M2 milestone. One of the key strengths was our agile approach to problem-solving. Whenever we encountered a roadblock, team members were proactive in suggesting alternative solutions, which kept the project moving forward without significant delays.

For instance, we initially struggled with the use case diagram and use case description. However we sat down and came up with a united decision for the solution to solve the issue.

The task was successful in identifying these strengths, which we plan to carry into our next milestone. It also provided a platform for team members to openly discuss any challenges they faced, fostering a culture of continuous improvement. The task was completed within the allocated time, aligning well with our overall project timeline, and setting us on a good path for M2.

Start Date: 6/10/2023
End Date: 6/10/2023

**Comment by samuelgjy** [comment]
Work Description

Describe the work done in detail:

Throughout the M1 project phase, our team consistently demonstrated a remarkable sense of urgency and responsibility, qualities that will undoubtedly serve us well as we transition into the next stage of the M2 project. One of our notable strengths was our adept time management skills which enabled us to effectively handle deadlines and prioritize tasks even while grappling with substantial workloads across various modules.

For example, our team initially struggled with the amount of workload for creating various use case diagrams and description which could set us back an additional several days. However, our team had recognized the urgency of the project and each member adhered to a strict schedule by setting daily goals and tracking progress against them.This strategic approach ensured that we remained on track and allowed us to promptly make any necessary adjustments.

The outcome of this concerted effort was a resounding success, as we were able to extract key details that highlighted the positive aspects of our work in M1.

This work does not need to be committed to the repository. 

This phase of work was also planned and executed within the allocated time frame which aligns with the overall project schedule, ensuring that the team is on track for completion in M2.

Start Date: 6/10/2023
End Date: 6/10/2023

**Comment by SaltedEggYok** [comment]
Work Description

Describe the work done in detail:

Reflecting on our M1 experience, I believe one of the things that went well is our consistent efforts to address the tasks required for this project. As the weeks progressed, we endeavored to maintain a steady pace in completing our project. Despite the challenge of balancing this project with other modules, we remained committed to ensuring that this project recieves sufficient attention.

Furthermore, during our meetings, everyone remained highly focused on the agenda, and deviations from our primary meeting objectives were rare, if not nonexistent. This commitment to staying on track allowed us to successfully achieve the goals we had set for each meeting.

Overall I believe these points were highly commendable of the team.

Start Date: 8/10/2023
End Date: 8/10/2023

**Comment by Thaddaeus-K** [comment]
Work Description

The team has demonstrated our ability to adapt well and to work together to achieve our common goal. Despite allocating our workload, when one team member faced difficulties, we are able to come together to help with the task to ensure that the project stays on track. When encountering difficulties or challenges, the team was able to come to a consensus quickly and move ahead with the project. It was quite evident that the exam was struggling quite a bit with the Functional Requirements and the Use Case Diagrams As we received different information and had varying perspectives. However, we were able to quickly clarify our doubts and push ahead. The team spirit in coming together to help each other was evident through this phase of the project as well. 

Start Date: 8/10/2023
End Date: 8/10/2023

**Comment by liewlucas** [comment]
Work Description

Describe the work done in detail:

Reflecting upon our M1 phase, the team has strong demonstrated the ability to communicate, and keep one another accountable. All of us makes the effort to turn up for any group meeting .A significant moment of turning was during a productive meeting after we had each completed our individual works and met up to cross check, rectify and improve upon each part as a team, this led to us having clearer insights on each other’s perspective, adjusting anything in the report that needed rectification, everyone was proactive in helping one another when stumbles or blockages were encountered during the process. I believe that the dynamic of helping one another is crucial in improving the overall quality of work produced, and that the process for M1 has set us on the right path.

Start Date: 8/10/2023
End Date: 8/10/2023
