### ISSUE TITLE
M1 Retrospection 2

### ISSUE THREAD

**Issue by SaltedEggYok** [SaltedEggYok/INF2001_P6-7#40]
Description of task: This task involves the retrospection of team members for the M1 milestone. 

Goal of task: The task aims to identify the strengths, weaknesses and any issues a team member might face. Some key questions include

**What could be improved?**
e.g. Team Dynamics, Team Manager, Task Allocation and Management, etc.

Success of the task is dependent on how well the team is able to discuss their issues and understand more about their teammates.

Allocated time: 3 day

Start Date:  5/10/2023
End Date:  8/10/2023

Owner: All group members
Status: In Progress

Priority: High

**Comment by davinlim23** [comment]
Work Description

Describe the work done in detail:

In this task, the team was able to discuss their respective viewpoints and what could be improved for the M2 project milestone. By discussing the specific strengths, weaknesses and other details of the team. The team was able to learn more about their teammates and ensure that each of these traits are accounted for in M2. In my personal opinion, I felt that the strength of the team lies in each member's individual ability in completing the tasks which were allocated to them, however, this is also a weakness as each member had different interpretations of the tasks which highlighted a lack of cohesiveness and direction amongst the team, underscoring my shortcomings as a leader. I recognize this need for improvement in steering the team's direction and have engaged in self reflection to ensure that I would enhance my leadership skills such that I would be more equipped to better manage the project for M2.

This task was a success as we were able to extract the key details which pertained to the negatives in M2. This work does not need to be committed to the repository. This phase of work was also planned and executed within the allocated time frame which aligns with the overall project schedule, ensuring that the team is on track for completion in M2.

Start Date: 6/10/2023
End Date: 6/10/2023

**Comment by ZIBINNG** [comment]
Work Description

Describe the work done in detail:

In this task, we took the time to critically evaluate our performance during the M1 milestone, focusing on areas that need improvement as we transition into the M2 milestone. One of the key takeaways was that while our team is technically skilled, we need to improve on our task allocation and management processes.

For example, communication. Although we have been using collaboration tools like Slack, there were instances where important updates or changes were not effectively communicated to all team members. This led to some confusion and rework. Going forward, we plan to hold regular stand-up meetings to ensure everyone is aligned and aware of any changes.

Overall, the task was successful in identifying these areas for improvement, and we are committed to implementing these changes in the M2 milestone. The task was completed within the allocated time and aligns well with our overall project schedule, ensuring that we are on track for M2.

Start Date: 6/10/2023
End Date: 6/10/2023

**Comment by samuelgjy** [comment]
Work Description

Describe the work done in detail:

In this task, we conducted a thorough assessment of our team's performance throughout the M1 project. While we certainly demonstrated a commendable sense of urgency and responsibility, attributes that will undoubtedly contribute to our success as we move into the next phase of the M2 project, there are areas where we can enhance our effectiveness such as communication.

From my perspective, there were occasions when the workload in certain weeks became quite demanding. In response, we collectively prioritized tasks that had impending deadlines. However, on some occasions, when we expected work to be completed by specific deadlines, our communication fell short, leading to confusion and occasional conflicts.

Going forward, this experience taught us the importance of adaptability, effective collaboration, and the value of clear communication. We plan to apply what we have experienced to future projects to optimize our performance and ensure timely project completion.

Overall, the task was successful in identifying these areas for improvement, and we are committed to implementing these changes in the M2 milestone. The task was completed within the allocated time and aligns well with our overall project schedule, ensuring that we are on track for M2.

Start Date: 6/10/2023
End Date: 6/10/2023

**Comment by SaltedEggYok** [comment]
Work Description

Describe the work done in detail:

Towards the conclusion of the project, there was a breakdown in communication among the different sections of the report for which we were responsible. For instance, our use case diagram underwent revisions during the final week before the submission deadline, but the corresponding use case descriptions were not updated to reflect these changes until a few days later.

I believe that we should try improve our communication by more effectively informing each other about our progress between workdays. This proactive approach will help prevent such oversights from occurring as easily in the future for M2 and M3.


Start Date: 8/10/2023
End Date: 8/10/2023

**Comment by liewlucas** [comment]
Work Description

Describe the work done in detail:

In this task, the team evaluated our performance during M1, reviewing any shortcomings of our team during the task.  A point that had been brought up was that towards the end nearing submission, everyone got very busy and occupied submission deadlines for all modules, as such our communication started to breakdown, and there was confusion at times as there were multiple changes toward the end to the report, and some formatting as well as content had been changed such as in the use case description that had multiple revisions from the original. we believe this could be because we all had different interpretations of some of the requirements.

Overall, while there had been some confusion where there was a period that the content kept changing, the team had eventually updated each other on what was changed. 
Moving forward, we believe that improved communication, proactive updates as well as established definitions of  trickier requirements can allow us to improve our dynamic and workload management as a team.


Start Date: 8/10/2023
End Date: 8/10/2023

**Comment by Thaddaeus-K** [comment]
At the start, the team was a bit unclear with our deliverables. To improve this, a quicker clarification of doubts will help us to better understand our project and allocate the tasks accordingly to each person. Furthermore, different team members had different interpretations of the deliverables which resulted in some work needing to be re-looked at a couple of times. Going forward, having face-to-face meetings would be effective as questions can be clarified on the spot to minimise errors and double work.

Start Date: 8/10/2023
End Date: 8/10/2023
