### ISSUE TITLE
M1 Retrospection 3

### ISSUE THREAD

**Issue by SaltedEggYok** [SaltedEggYok/INF2001_P6-7#41]
Description of task: This task involves the retrospection of team members for the M1 milestone. 

Goal of task: The task aims to identify the strengths, weaknesses and any issues a team member might face. Some key questions include

**What will be committed for improvement in the next milestone?**

Success of the task is dependent on how well the team is able to discuss their issues and understand more about their teammates.

Allocated time: 3 day

Start Date:  5/10/2023
End Date:  8/10/2023

Owner: All group members
Status: In Progress

Priority: High

**Comment by davinlim23** [comment]
Work Description

Describe the work done in detail:

In this task, the team was able to discuss their respective viewpoints and what would be committed for improvement in M2. By understanding what needed to be improved as a team in M2, one member could be designated to oversee and drive collective efforts towards the enhancements of the project. In my personal opinion, I felt that the primary aspect which requires improvement lies in the communication amongst the team members, particularly with regards to team dynamics as I felt that while each member was able to communicate their issues to each other, certain issues arose as a result of tackling the task without considering the previous tasks and ensuring that a clear project flow, resulting in an obvious display of slightly disjointed individual parts. One simple example was a lack of uniformity in using the same word for concepts that essentially conveyed the same meaning. This was an aspect that I felt that both the team and I would need to improve on as I feel that while everyone needs to ensure that they have understood the tasks assigned to them, it also falls within my responsibility as a team lead to ensure clear guidance and direction amongst the team. 

This task was a success as we were able to extract the key details which pertained to the areas for improvement in M2. This work does not need to be committed to the repository. This phase of work was also planned and executed within the allocated time frame which aligns with the overall project schedule, ensuring that the team is on track for completion in M2.

Start Date: 6/10/2023
End Date 6/10/2023

**Comment by ZIBINNG** [comment]
Work Description

Describe the work done in detail:

In this task, we engaged in a comprehensive discussion to identify what specific actions will be committed for improvement as we move into the M2 milestone. One of the primary areas we identified for improvement is task allocation and time management. While we have been diligent in completing tasks, there was a noticeable inefficiency in how tasks were distributed and managed, leading to bottlenecks and last-minute rushes.

For example, we need to improve on our documentation. While we did maintain some level of documentation, it was not consistent or comprehensive enough to be useful for new team members or for future reference. We plan to standardize our documentation practices, making it a mandatory part of our development process.

The task was successful in pinpointing these areas for improvement, and we are all committed to making these changes in the M2 milestone. The task was completed within the allocated time and aligns well with our overall project schedule, ensuring that we are on track for M2.

Start Date: 6/10/2023
End Date: 6/10/2023

**Comment by samuelgjy** [comment]
Work Description

Describe the work done in detail:

In this task, we engaged in a comprehensive discussion to identify what specific actions will be committed for improvement as we move into the M2 milestone. One of the primary areas we identified for improvement is documentation. While our team demonstrated exemplary in the work produced, however there were some issues in terms of documentation which highlight the lack of cohesiveness in ensuring that the report is standardized and comprehensive.

For instance, during the M1 project phase, we consistently produced high-quality work in terms of the project's core objectives. However, when it came to documenting our progress and findings, inconsistencies and gaps became evident. These discrepancies ranged from variations in formatting and reporting styles to occasional omissions of critical details. As a result, our project reports did not consistently adhere to a standardized format which could have hindered our ability to convey the full scope of our work effectively.

The task was successful in identifying these areas for improvement, and we are all committed to making these changes in the M2 milestone. The task was completed within the allocated time and aligns well with our overall project schedule, ensuring that we are on track for M2.

Start Date: 6/10/2023
End Date: 6/10/2023

**Comment by SaltedEggYok** [comment]
Work Description

Describe the work done in detail:

For our next and subsquent milestones I believe we will be able to commit the following.
More robust and frequent communication amongst team members. More regular and detailed updates on progress, changes, and challenges will be shared to ensure everyone is well-informed. We will also revisit and clarify individual responsibilities within the team to ensure everyone understands their roles and contributions to the project. Additionally, we will also establish clear documentation standards and templates for various project components to ensure consistency and alignment throughout the project, as during the project up till the final few weeks, words such as "job" and "work" were still being used interchangibly to mean different things.

Start Date: 8/10/2023
End Date 8/10/2023

**Comment by liewlucas** [comment]
Work Description

Describe the work done in detail:

The team has took time to evaluate what we can do better following M1, and a few points such as documentation, communication and established definitions are among the list we came up with for improvement.

We agreed that more proactive efforts in communication will be taken, by updating each other on various changes needed or made at the time of rectification as well as improved documentation on our progress, attempting to list out the clear definitions of terms or requirements, as well as changes. This would allow for a fully documented, communicative team dynamic with clear insights on our goal and would allow us to work more effectively during the coming milestones.

Start Date: 8/10/2023
End Date: 8/10/2023

**Comment by Thaddaeus-K** [comment]
The team probably could do better in our documentation to update each other on the work done. Furthermore, more emphasis could be placed when documenting such as terminologies to be used, as there were discrepancies throughout the report initially where different parts written by different members were using different terminologies. Other than improvements, I think we would commit to maintaining our team’s time management to complete the tasks at hand which will be crucial in the upcoming milestones. 

Start Date: 8/10/2023
End Date: 8/10/2023
