### ISSUE TITLE
Improvements to Use Case Descriptions

### ISSUE THREAD

**Issue by davinlim23** [SaltedEggYok/INF2001_P6-7#42]
Description of task: This task involves the improvements to the use case descriptions which require refining based on the feedback provided in M1. 

Goal of task: The task aims to provide improvements to the use case descriptions in preparation for designing the sequence diagrams.

Success of the task depends on the accurate detailing of all improvements which are required for the respective use cases, while the new descriptions remain relevant and precise.

Allocated time: 3 days

Start Date:  16/10/23
End Date:  18/10/23

Owner: Samuel
Status:  To Do

Priority:  High

**Comment by samuelgjy** [comment]
Work Description

Describe the work done in detail:

In this task, we focused on refining the use case descriptions based on the feedback provided during M1. The improvements were made to ensure that the descriptions are more detailed, precise, and relevant to prepare for the subsequent task of designing sequence diagrams. Specifically, we added additional information, clarified ambiguities, and removed any redundant or irrelevant content from the use case descriptions.

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule.

Start Date: 18/10/23
End Date: 18/10/23
