### ISSUE TITLE
2.2.1.2 Create Coach Management Module

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#47]
Description of task: The task involves the creation of coach management module which includes boundary, control, interface classes that is responsible for handling interaction between the external entities and system in which they act as interfaces for data input and output.

Goal of task: The objective of this task is to create coach management module responsible of how the the coach management of the coach system works.

Success of the task is dependent based on how successful the coach management module are implemented and integrated seamlessly into the system. 

Allocated time: 1 week

Start Date: 05/10/23
End Date: 12/10/23

Owner: Lucas Liew
Status: Completed

Priority: High

**Comment by liewlucas** [comment]
The task at hand involved the development of a coach management module, incorporating boundary, control, and interface classes to facilitate the interaction between external entities and our system, acting as interfaces for data input and output. The primary goal was to establish an efficient and robust coach management module that seamlessly integrates with our coach system. We have successfully achieved this objective. The creation of enumeration 'enum_CoachStatus,' 'Coach' entity, 'CoachControl' control class which implements an 'iCoach' interface and 'CoachControlUI' boundary class. This well-structured module not only enhances the coach management functionalities but also contributes to the overall system's smooth operation. The task's success is evident in the seamless integration of these components into our system, enabling efficient data handling and interaction between external entities.
