### ISSUE TITLE
2.2.1.3 Create Job Management Module

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#48]
Description of task: The task involves the creation of boundary, control and interface classes that is responsible for handling interaction between the external entities and system. These together will form the job management module.

Goal of task: The objective of this task is to create a job management module that manages the job allocations and specifications.

Success of the task is dependent on how successfully the job management module is implemented and integrated seamlessly into the system.

Allocated time: 1 week

Start Date: 28/09/23
End Date: 05/10/23

Owner: To Be Scheduled
Status: To Do

Priority: High

**Comment by Thaddaeus-K** [comment]
Description of work done:
Boundary, control and interface classes were created to make up the Job Management Module. Boundary classes such as Google Maps API and the Job Control UI were created which works with the control Job Control control class which implements the iJob interface. The interface allows managers to allocate and update job allocations to the coach staff.

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule.

Start Date: 28/09/23
End Date: 05/10/23
