### ISSUE TITLE
2.2.1.4 Create Manager Functionality Module

### ISSUE THREAD

**Issue by samuelgjy** [SaltedEggYok/INF2001_P6-7#49]
Description of task: The task involves the creation of boundary and control classes that is responsible for allowing managers to manage coach staff and job allocations. These together will form the manager functionality module.

Goal of task: The objective of this task is to create a manager functionality module that manages the coach staff and job allocations.

Success of the task is dependent on how successfully the manager functionality module is implemented and integrated seamlessly into the system.

Allocated time: 1 week

Start Date: 28/09/23
End Date: 05/10/23

Owner: To Be Scheduled
Status: To Do

Priority: High

**Comment by Thaddaeus-K** [comment]
Description of work done:

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule.

Start Date: 28/09/23
End Date: 05/10/23

**Comment by ZIBINNG** [comment]
I have successfully completed the task of creating the manager functionality module within the allocated time frame of one week. The module includes both boundary and control classes that enable managers to effectively manage coach staff and job allocations. The implementation has been seamlessly integrated into the existing system, fulfilling the task's objective.

Start Date: 28/09/23
End Date: 05/10/23
