### ISSUE TITLE
2.1.2 Identifying Candidate Class

### ISSUE THREAD

**Issue by davinlim23** [SaltedEggYok/INF2001_P6-7#51]
Description of task: The task entails the identification of candidate class from the noun extraction preceding task 2.1.1.

Goal of task: The objective of this task is to correctly identify candidate classes in preparation for the design of the class diagram. 

Success of the task is dependent on the correct identification of all candidate classes.

Allocated time: 1 day

Start Date: 26/9/23
End Date: 27/9/23

Owner: Samuel Goh
Status: To Do

Priority: High

**Comment by samuelgjy** [comment]
Work Description:

In this task, I focused on the identification of candidate classes based on the noun extraction that was performed in the preceding task . These nouns were to identify potential candidate classes, which are essential objects or entities that will play a significant role in the software system. The process involved documenting the findings, which encompassed naming the candidate classes, specifying their possible attributes, and providing the reasoning behind their selection.

The work does not need to be committed to the repository.

The completion of this task does not have a direct impact on the overall project deadline and the deadline remains unaffected and the original criteria remain in place, which is the correct identification of candidate classes based on the noun extraction from Task 2.1.1

Start Date: 27/9/23
End Date: 27/9/23
