### ISSUE TITLE
2.2.1.5 Create Coach Staff Functionality Module

### ISSUE THREAD

**Issue by ZIBINNG** [SaltedEggYok/INF2001_P6-7#52]
Description of task: This task involves creating an entity class, a control class and a boundary class that are contained in the Coach Staff Functionality module.

Goal of task: The task aims to ensure that the control classes contains all the relevant attributes and behaviour.

Success of the task is dependent such that it should be created to cover all relevant attributes and behaviors associated with the specific concept defined within the project scope. This means ensuring that it encapsulates all essential characteristics of the coach staff functionality module.

Allocated time: 1 week

Start Date: 28/09/2023
End Date: 05/10/2023

Owner: To Be Scheduled
Status: To Do

Priority: Medium

**Comment by davinlim23** [comment]
Work Description

Describe the work done in detail: The respective boundary, control and entity classes were created based on the identification of candidate classes. The attributes of the entity classes were properly encapsulated and the control classes utilize methods to retrieve attributes from the entity classes. Boundaries act as the UI of the system for the user to interact with. 

This work does not need to be committed to the repository. This phase of work was also planned and executed within the allocated time frame which aligns with the overall project schedule, ensuring that the team is on track for completion in M2.


Start Date: 28/10/23
End Date: 05/10/23
