### ISSUE TITLE
3.1.2 Software Design Pattern

### ISSUE THREAD

**Issue by davinlim23** [SaltedEggYok/INF2001_P6-7#55]
Description of the task: This task involves the researching and deciding on a suitable Software Design Pattern to be utilized within the system.

Goal of the task: The goal of this task is to modify some classes within the class diagram to showcase the correct application of the software design patterns in our application. The choice of software design pattern must be properly justified and explained.

Success of this task is dependent on the correct identification of suitable Software Design Patterns which can be used to represent the design of the application.

Allocated time: 4 days

Start Date: 8/11/2023
End Date: 12/11/2023

Owner: Wong Yok Hung
Status: In Progress

Priority: Medium

**Comment by SaltedEggYok** [comment]
Work Description

Describe the work done in detail:

In this task, all 23 software design patterns were researched on, and the consensus was that the Observer Pattern as well as the Factory Design Pattern are the most fitting for our project. 

Additional classes that fit the patterns were written and integrated into our current class diagram to accomplish the tasks.

Justification and proper explanation were writen and added to the report.

This work does not need to be committed to the repository. This phase of work was also planned and executed within the allocated time frame which aligns with the overall project schedule, ensuring that the team is on track for completion in M3.

Start Date: 8/11/2023
End Date 12/11/2023
