### ISSUE TITLE
3.3.2 Concept, Flow and Design of Application

### ISSUE THREAD

**Issue by davinlim23** [SaltedEggYok/INF2001_P6-7#56]
Description of the task: This task involves the accurate documenting of the concept, flow and design of the application and how it corresponds and fulfills all use cases.

Goal of the task: The goal of this task is to ensure that the application is representative of all requirements provided by the client to ensure that the app is fully functional.

Success of this task is dependent on the correct description of the concept, flow and design of the application and proper explanations on why specific features are implemented as per client requirements.

Allocated time: 4 days

Start Date: 14/11/2023
End Date: 21/11/2023

Owner: Ng Zi Bin
Status: In Progress

Priority: High

**Comment by ZIBINNG** [comment]
In completing the task, detailed documentation was produced to define the application's concept, user flow, and design, ensuring alignment with client requirements. The documentation features clearly articulated relationships between the boundary, control, and entity classes, with well-encapsulated attributes and methodical access via control classes. The user interface, represented by boundary classes, was designed to facilitate user interaction seamlessly.

This documentation phase was conducted within the expected time frame, adhering to the planned schedule. The timely completion of this task contributes positively to the project's momentum, ensuring that the team remains on course for the upcoming milestones in M3.

By fulfilling all the objectives outlined for this task, including a precise explanation of the application's concept, flow, and design, and a clear justification for each feature, this task is now ready to be closed.

Start Date: 14/11/2023
End Date: 21/11/2023
