### ISSUE TITLE
1.1.4 Functional Requirements (Replaces Task 05)

### ISSUE THREAD

**Issue by SaltedEggYok** [SaltedEggYok/INF2001_P6-7#9]
Task Description: This task involves the analyzing the information provided by the client to determine the functional requirements which are required to be implemented in the application.

Goal of task: This task aims to establish all functional requirements which are required to be implemented within the application.

Success of the task is determined by the successful identification of all functional requirements which align with the client's vision of the application.

Allocated time: 2 hours.

Start Date: 13/9/2023
End Date: 13/9/2023

Prioritity: High

**Comment by davidlane23** [comment]
Work Description

**Describe the work done in detail:**
In this task, the functional requirements were identified by consolidating all information which was acquired from the initial interview with the client and the questionnaire. Confirmation with the client was also obtained which ensured the alignment of the requirements with the client's vision.

With the successful identification and confirmation of the functional requirements, the task has been successfully completed.

Start Date : 13/9/2023
End Date: 13/9/2023
